function plotSine()

    % generate new figure
    hFigureHandle = generateFigure(8, 6);
    
    % set output path relative to script location and to script name
    [cPath, cName] = fileparts(mfilename('fullpath'));
    cOutputFilePath = [cPath '/../graph/' strrep(cName, 'plot', '')];

    % read audio and generate plot data
    [t, x] = getData();

    %plot
    plot(t, x);
    xlabel('$t\; [\mathrm{s}]$');
    ylabel('$x_\mathrm{sine}(t)$');
%     set(gca, 'XTickLabel', [])
%     set(gca, 'YTickLabel', [])
    axis([t(1) t(end) -1 1])

    annotation(hFigureHandle, 'doublearrow', [0.37 0.57],...
        [0.873541666666667 0.873541666666667], 'Color', 'black',...
        'Head2Width', 6,...
        'Head2Length', 6,...
        'Head1Width', 6,...
        'Head1Length', 6);
    annotation(hFigureHandle, 'textbox', [0.38 0.8 0.026 0.067],...
        'Color', 'black',...
        'EdgeColor', 'none',...
        'String', {'period length'},...
        'FontSize', 8,...
        'interpreter', 'latex');

    annotation(hFigureHandle, 'doublearrow', [0.18 0.18],...
        [0.34 0.72], 'Color', 'black',...
        'Head2Width', 6,...
        'Head2Length', 6,...
        'Head1Width', 6,...
        'Head1Length', 6);
    annotation(hFigureHandle, 'textbox', [0.1 0.28 0.026 0.067],...
        'Color', 'black',...
        'EdgeColor', 'none',...
        'String', {'amplitude'},...
        'FontSize', 8,...
        'interpreter', 'latex');

    % write output file
    printFigure(hFigureHandle, cOutputFilePath)
end

function [t, x] = getData()

    [x,t] = generateSineWave(4, 1, 8000);
    x = .5*x;
end

